### ISSUE TITLE
shadingGroup.addMember always fails

### ISSUE THREAD

**Issue by mjmvisser** [LumaPictures/pymel#111]
xform, shape = pm.polySphere()
    pm.SCENE.initialShadingGroup.addMember(shape)
    
    # Warning: Cannot add the following items to the set since the set has restrictions on membership: polySphere2 # 
    # Warning: None of the items can be added to the set # 

Instead, you have to do this:

    pm.sets(pm.SCENE.initialShadingGroup, forceElement=shape)

**Comment by elrond79** [comment]
The problem here is that the second object returned by pm.polySphere() is NOT a shape, it is a 'polySphere' node, which is actually a DG node which generates a mesh. So, for example, this works:

```
xform = pm.polySphere()[0]
pm.SCENE.initialShadingGroup.addMember(xform.getShape())
```

**Comment by mjmvisser** [comment]
Sorry, bad example, but it still doesn't work:

    s = pm.shadingNode('blinn', asShader=True)
    sg = pm.sets(renderable=True, noSurfaceShader=True, empty=True, name='blinnSG')
    s.outColor.connect(sg.surfaceShader)
    xform = pm.polySphere()[0]
    sg.addMember(xform.getShape())
    
    # Error: Cannot add the following items to the set since they would break the exclusivity constraint: pSphereShape1 #

**Comment by elrond79** [comment]
Ah, gotcha. The problem here is that all shading groups are actually members of a partition - meaning that no object can be in two sets within that set. In our case, the sphere is already in the initialShadingGroup, so it can't be in blinnSG too (thus the stuff about the exclusivity constraint).
In vanilla maya.cmds, you generally get around this by using sets(obj, forceElement="blinnSG")... and while you can use pm.sets(obj, forceElement=...), it seems there's currently no equivalent method wrapped onto the ObjectSet / ShadingGroup classes.

So, I've added a forceElement method to ObjectSet, so the node's interface mirrors that of the cmds.sets interface:

https://github.com/LumaPictures/pymel/commit/949e3a2e6fdf42cfc179ba974e25cc72cbe866f4

**Comment by 1485863714** [comment]
![C)ZR@O6)KZ@{%N_D{GMR)MG](https://user-images.githubusercontent.com/52433104/80165500-3419ed80-860e-11ea-9d9c-b177e93fc5f6.png)
![(%RC$GPZ3 7@Q90SA%L$D1C](https://user-images.githubusercontent.com/52433104/80165501-34b28400-860e-11ea-9211-c1796cd950d9.jpg)

hello, I want to assign the material to the selected object ,but Warning: line 1018: Cannot add the following items to the set since the set has restrictions on membership: displacementShader1 // 
// Warning: line 1018: None of the items can be added to the set // 

anyone can help me?   thanks!!!
