### ISSUE TITLE
pm.delete on a deleted PyNode will delete nodes of the same unique name rather than raising an error.

### ISSUE THREAD

**Issue by ldunham1** [LumaPictures/pymel#396]
I would expect calling delete on a deleted PyNode to raise an error even if another node has the same unique name.

```
import pymel.core as pm

# -- Create a transform and get the pm.Transform object
node = pm.createNode('transform', name='test_obj')
# -- Delete it
pm.delete(node)

# -- This still resolves
print(node.name())
# 'test_obj'

# -- Create a joint of the same name
pm.createNode('joint', name='test_obj')
# -- Delete the original pm.Transform will delete the new joint of the same name rather than raising an error.
pm.delete(node)
```

**Comment by elrond79** [comment]
This would violate a basic tennant of pymel, which is that each PyNode has a strong relationship, not with the name (which would more closely resemble how maya.cmds works), but with the underlying node object itself.  Ie, consider the scenario where you have two nodes, A and B, and rename them (respectively) newA and A.  We want the PyNodes to follow the actual nodes in this scenario, not the names.
(If you're familiar with the api, PyNodes are similar to MObjects in this respect, in that you can query the name of a deleted MObject, and if you try to delete an already deleted MObject, it won't simply delete any similarly named nodes.)
Also, while we could add behavior to Pymel's delete function, to check if any nodes were deleted, and if so, delete any similarly named, this would have two complications: one, there would be a potential performance hit, as we would have to validate all nodes prior to deletion... And with long lists of nodes, this is not insignificant.  Secondly, and more importantly, it encourages bad and potentially dangerous behavior.  Once a PyNode is deleted, doing operations on it will generally raise an error, and that's the mindset we want to encourage.
Finally, if you know some of your nodes might be deleted, and you want this behavior, then there is a simple workaround - simply call .name() first yourself, and then delete those. This is all that Pymel would be doing under the hood if we were to implement this feature anyway.  Or, simply store lists of names in the first place, if you know you want your behavior to follow the name.

**Comment by elrond79** [comment]
Oh my - my mistake! I just reread your issue, and you were arguing in favor of the desired behavior! Yes, we will look into this!

**Comment by ldunham1** [comment]
Perfect thanks. Apologies for not making my issue clearer.

**Comment by ldunham1** [comment]
Argh - accidental close. Unfamiliar - how can I reopen?

**Comment by elrond79** [comment]
Looks like you figured it out. =)

...and your description was perfectly clear - I just need to not respond to issues first thing after waking up, I guess. =)

Re: the issue though... it turns out to be a little trickier than I had thought.  It seems that most pymel operations will operate in this manner - ie, warn when resolving to a name, but then operate on that name if it exists, and only error if it no longer does.

I'm not a fan of this behavior - I think it should error as you do - but changing this would probably break a lot of "functioning" code.  (Ie, cases where folks have long lists of nodes, one or two of which are deleted, and they would like it to essentially "ignore" the deleted nodes and just operate on the non-deleted ones... and/or actually DO want the deleted ones to just operate on nodes of the same name).

I think I'll perhaps make this a configurable option - so that instead of printing a warning, it simply errors.  It would then give the "desired" behavior in your example, with one exception - it would also error when simply printing the deleted node's name.  While I can see an argument for still allowing access to a deleted node's name without error, I think there's an at-least-equally-valid argument to be made for also erroring on name access... and from a practical standpoint, trying to allow name-access, but not anything else, would be very difficult to do.  If you do have situations where you really want to know the name of deleted nodes, then you can probably temporarily turn off the error-on-deleted-nodes setting using a try/finally clause.

**Comment by elrond79** [comment]
addressed in:

https://github.com/LumaPictures/pymel/commit/44a2f38decf7a7997958cbaae55ae0b0874df643
https://github.com/LumaPictures/pymel/commit/680a5a14417a449c5db82d5984ccc52a79304b96
